# Generated by Django 5.0.7 on 2026-08-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_attendance_overtime_hours_attendance_total_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='overtime_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
